# -*- coding: utf-8 -*-
"""minutes genaraor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOdhmuj1US0hIAM2mQ_MgTr_PgasXotW
"""

# Create structured meeting minutes

minutes = (

"Meeting Title: meeting_title,

"Date":

date,

"Time": time,

"Participants": ", ".join(participants_list),

"Agenda": "; ".join(agenda_list),

"Decisions Taken": "; ".join(decisions_list),

"Action Items":"; ".join(actions_list),

"Prepared By": prepared_by,

"Generated On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")

}

# Convert to DataFrame

df = pd.DataFrame (list(minutes.items()), columns=["Field", "Details"])

print("\n Meeting Minutes Generated Successfully\n")

display(df)

#Save as CSV

df.to_csv("meeting_minutes.csv", index=False)

print("\n File saved as meeting_minutes.csv")



import pandas as pdimport randomprint("TIMETABLE GENERATORIn")# User Inputssubjects_input = input("Enter subjects (comma separated):“)days_input - input("Enter days (comma separated):")periods_per_day = int(input ("Enter number of periods per day:"))# Process Inputssubjects = [s.strip() for s in subjects_input.split(", ")if s.strip()]days = [d.strip() for d in days_input.split(",")if d.strip()]# Validationif len(subjects) == 日 or len(days) == θ or periods_per_day<s 0:print("Invalid input. Please try again.")else:timetable =ffor day in days:timetable[day] = random.choices(subjects, k=periods_per_day)# Create DataFramedf = pd.DataFrame(timetable)df.index = [f"Period (i+1)" for 1 in range(periods_per_day)]print("InTimetable Generated Successfullyin")display(df)# Save timetabledf.to csv("timetable.csv")print("\nTimetable saved as timetable.csv")